# Copyright 2020 New Zealand Brain Research Institute
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# export_data.R

###############################################################################

source("initialise_environment.R")

source("utils.R")

date_string = format(lubridate::ymd(lubridate::today()))

###############################################################################

# Small set of first-pass data consistency checks / modifications
sanitise_data <- function(data) {
  cleaned_data <- data

  # Makes sure things work as expected
  cleaned_data <- cleaned_data %>%
    ungroup()

  # Check ID columns
  nrows = nrow(cleaned_data)
  cleaned_data <- cleaned_data %>%
    filter(across(
      matches("subject_id") | matches("session_id"),
      ~ !is.na(.x)
    ))
  # Warn if missing
  nrows_removed = nrows - nrow(cleaned_data)
  if (nrows_removed > 0) {
    warning(paste("Removed", nrows_removed, "rows missing subject/session IDs."))
  }

  return(cleaned_data)
}

###############################################################################
# Load from database, with minimal preprocessing

participants <- chchpd::import_participants()
participants <- participants %>%
  sanitise_data() %>%
  mutate(across(c(participant_group, ethnicity), as.factor)) %>%
  mutate(across(c(excluded_from_followup), as.logical)) %>%
  rename(
    age_at_diagnosis = diagnosis_age,
    age_at_symptom_onset = symptom_onset_age
  ) %>%
  # Drop extraneous info
  select(-survey_id, -participant_status, -excluded_from_followup, -age_today)

# -----------------------------------------------------------------------------

sessions <- chchpd::import_sessions(exclude = FALSE)
sessions <- sessions %>%
  sanitise_data() %>%
  # Exclude anything missing a date, or only scheduled to happen
  filter(!is.na(session_date)) %>%
  filter(session_date <= lubridate::today()) %>%
  # Tidy up exclusion information
  mutate(across(c(study_excluded), as.logical)) %>%
  mutate(study_excluded = replace_na(study_excluded, FALSE)) %>%
  mutate(study_group = replace_na(study_group, "Unknown")) %>%
  mutate(study_excluded = (study_excluded | (study_group == "Excluded"))) %>%
  group_by(session_id) %>%
  mutate(study_excluded = any(study_excluded)) %>%  # Conservative!
  ungroup() %>%
  # Tidy up and collate other information across sessions
  group_by(session_id) %>%
  arrange(study) %>%
  mutate(studies = list(as.character(study))) %>%
  mutate(mri_scan_no = na_if(mri_scan_no, "None")) %>%
  fill(mri_scan_no, .direction = "downup") %>%
  ungroup() %>%
  # Remove study-specific variables and duplicate sessions
  select(-session_label, -session_suffix, -study, -study_group) %>%
  distinct(.keep_all = TRUE)

# @m-macaskill: Convention for e.g. `study_excluded` is to go off positive
# evidence, as some of the data predates some of the auto-validations that
# generate these fields (i.e. exclude on `TRUE` but not `NA`). See e.g. the
# source for `chchpd::import_sessions()` itself.
# As such, we simply replace `NA` with `FALSE` for these variables.
#sessions %>% count(study_excluded) %>% print(n = Inf)

# Check we have got unique sessions
stopifnot(
  sessions %>%
    group_by(session_id) %>%
    filter(n() > 1) %>%
    plyr::empty()
)

# -----------------------------------------------------------------------------

neuropsych <- chchpd::import_neuropsyc(concise = TRUE)
neuropsych <- neuropsych %>%
  sanitise_data() %>%
  mutate(across(c(diagnosis, diagnosis_baseline, np_group), as.factor)) %>%
  # Tidy up exclusion information
  mutate(np_excluded = replace_na(np_excluded, FALSE)) %>%
  # Drop autogenerated baselines: we will regenerate our own later
  select(
    -date_baseline, -global_z_baseline, -diagnosis_baseline,
    -session_number, -years_from_baseline, -FU_latest
  ) %>%
  # Use data from NPI CSV below explicitly
  select(-npi) %>%
  # Add tag to differentiate from other session types
  mutate(neuropsych_session = TRUE)

# -----------------------------------------------------------------------------

# http://npitest.net/about-npi.html

npi <- read_csv(file.path("..", "Data", "npi_2020-07-13_v2.csv"))
# Remove columns that are irrelevant / already covered by `sessions` and
# `neuropsych` / specific to other domains
npi <- npi %>%
  sanitise_data() %>%
  select(
    -X1, -subject_id, -record_id.x, -record_id.y,
    -npi_data_missing, -npi_data_missing_reason, -npi_session, -npi_notes,
    -npi_occ_disruption_total, -npi_freq_sev_total_calc
  ) %>%
  select(-matches("session_[^i][^d]")) %>%
  select(-contains("redcap")) %>%
  select(-matches("npi_[a-f]_")) %>%
  select(-matches("npi_[h-l]_")) %>%
  rename_with(~ gsub("npi_", "NPI_", .x, fixed = TRUE)) %>%
  rename_with(~ gsub("NPI_g_", "NPI_apathy_", .x, fixed = TRUE)) %>%
  rename(NPI_occ_disruption_total = NPI_occ_disruption_total_calc) %>%
  rename_with(
    ~ paste("NPI_", .x, sep = ""), !starts_with("NPI_") & !session_id
  ) %>%
  mutate(across(matches("_present"), as.logical))

# -----------------------------------------------------------------------------

medications <- chchpd::import_medications(concise = FALSE)
medications <- medications %>%
  sanitise_data() %>%
  select(session_id, LED, other_medications) %>%
  mutate(taking_antidepressants = FALSE)
# Find antidepressants
# https://www.healthnavigator.org.nz/medicines/a/antidepressants/
for (drug_name in c(
  "citalopram", "escitalopram", "fluoxetine", "paroxetine", "sertraline",
  "venlafaxine",
  "amitriptyline", "clomipramine", "imipramine", "doxepin", "nortriptyline",
  "moclobemide", "phenelzine", "tranylcypromine",
  "mirtazapine"
)) {
  # Fuzzy match drug names
  medications <- medications %>%
    rowwise() %>%
    mutate(match = agrepl(
      drug_name, other_medications, max.distance = 0.1, ignore.case = TRUE
    )) %>%
    ungroup() %>%
    mutate(
      taking_antidepressants = (taking_antidepressants | match),
      match = NULL
    )
}
# medications %>% filter(taking_antidepressants) %>% View()
medications <- medications %>%
  select(-other_medications)

# Explode medication lists to individual drugs
# Useful for looking at summary stats and assessing misspellings!
# medications %>%
#   ungroup() %>%
#   select(session_id, other_medications) %>%
#   # One medication per row
#   mutate(other_medications = str_split(other_medications, ", ")) %>%
#   unnest(other_medications) %>%
#   # Crude removal of dose to help summary groups
#   mutate(other_medications = gsub("(.*) [0-9].*", "\\1", other_medications)) %>%
#   mutate(other_medications = tolower(other_medications)) %>%
#   # Summarise occurrences
#   count(other_medications) %>% #arrange(desc(n)) %>% View()
#   # Fuzzy match named medications
#   # https://stackoverflow.com/a/30912546
#   rowwise() %>%
#   mutate(match = agrepl("citalopram", other_medications, max.distance = 0.1, ignore.case = TRUE)) %>%
#   ungroup() %>%
#   filter(match) %>% print()

# -----------------------------------------------------------------------------

hads <- chchpd::import_HADS(concise = TRUE)
hads <- hads %>%
  sanitise_data()

# -----------------------------------------------------------------------------

# https://www.movementdisorders.org/MDS/MDS-Rating-Scales/MDS-Unified-Parkinsons-Disease-Rating-Scale-MDS-UPDRS.htm

motor_scores <- chchpd::import_motor_scores()
motor_scores <- motor_scores %>%
  sanitise_data() %>%
  rename(UPDRS_motor_score = Part_III, Hoehn_Yahr = H_Y) %>%
  mutate(
    Hoehn_Yahr = factor(
      Hoehn_Yahr,
      levels = c(0.0, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0),
      ordered = TRUE
    ),
    UPDRS_source = factor(UPDRS_source)
  )

# Import raw MDS-UPDRS scores for apathy question
# Q1.5 is apathy
mds_updrs = chchpd::import_MDS_UPDRS(concise = FALSE)
mds_updrs <- mds_updrs %>%
  sanitise_data() %>%
  mutate(
    UPDRS_apathy = factor(
      Q1_5,
      levels = c(0, 1, 2, 3, 4),
      labels = c("Normal", "Slight", "Mild", "Moderate", "Severe"),
      ordered = TRUE
    )
  ) %>%
  select(session_id, UPDRS_apathy, UPDRS_date)

# Note that some subjects have data that predates the MDS-UPDRS (i.e. from the
# 1987 UPDRS). However, we ignore those for now as that version does not seem
# to contain any apathy-specific questions.
# old_updrs = chchpd::import_old_UPDRS()

###############################################################################
# Join all the records together, linked by subject or session IDs

# Use `inner_join` to maintain the exclusions specific to the individual
# databases
full_data <-
  inner_join(participants, sessions, by = "subject_id") %>%
  left_join(neuropsych, by = "session_id") %>%
  left_join(npi, by = "session_id") %>%
  left_join(medications, by = "session_id") %>%
  left_join(hads, by = "session_id") %>%
  left_join(motor_scores, by = "session_id") %>%
  left_join(mds_updrs, by = "session_id")

###############################################################################
# Inclusion/exclusion criteria, and generate some derived metrics

# Derive each subject's date of first visit
# This will often be a screening session that is subsequently excluded
full_data <- full_data %>%
  arrange(subject_id, session_date) %>%
  group_by(subject_id) %>%
  mutate(
    first_session_date = first(session_date),
    years_since_first_session = years_between(first_session_date, session_date),
    age_at_first_session = first(age),
    session_number = row_number()
  ) %>%
  ungroup()

# Filter to participants of interest & neuropsych sessions only
full_data <- full_data %>%
  # Inclusion (participant): PD group
  filter(participant_group == "PD") %>%
  # Inclusion (session): neuropsych assessments performed
  filter(!is.na(neuropsych_session)) %>%
  select(-neuropsych_session) %>%
  # Exclusion (session): screening only
  filter(!map_lgl(studies, ~ "Screening PD" %in% .x))

# Generate some useful within-subject summaries
full_data <- full_data %>%
  arrange(subject_id, session_date) %>%
  group_by(subject_id) %>%
  mutate(
    neuropsych_assessment_number = row_number()
  ) %>%
  ungroup()

# Remove invalid sessions
full_data <- full_data %>%
  # Exclusion (session): other exclusions apply
  filter((study_excluded == FALSE) & (np_excluded == FALSE)) %>%
  select(-study_excluded, -np_excluded)

# Remove obvious data inconsistencies
full_data <- full_data %>%
  # Exclusion (session): long gaps between main and NPI sessions
  filter(
    is.na(NPI_date) | (abs(days_between(session_date, NPI_date)) <= 90)
  ) %>%
  # Remove invalid motor scores for same reason
  mutate(
    valid_UPDRS_date = (
      is.na(UPDRS_date) | (abs(days_between(session_date, UPDRS_date)) <= 90)
    ),
    across(
      starts_with("UPDRS_") | Hoehn_Yahr, ~ replace(.x, !valid_UPDRS_date, NA)
    ),
    valid_UPDRS_date = NULL
  )

# For convenience
full_data <- full_data %>%
  arrange(subject_id, session_date)

colnames(full_data)

###############################################################################
# Summaries

dim(full_data)
full_data$subject_id %>% unique %>% length
#full_data$session_id %>% unique %>% length
full_data %>% count(full_assessment) %>% print(n = Inf)
#full_data %>% count(study) %>% print(n = Inf)
#full_data %>% count(study_group) %>% print(n = Inf)
#full_data %>% count(diagnosis_baseline) %>% print(n = Inf)
full_data %>% count(diagnosis) %>% print(n = Inf)
full_data %>% summarise(across(.fns = ~ sum(is.na(.x)))) %>% print(width = Inf)

###############################################################################
# Save to file

saveRDS(
  full_data,
  file.path("..", "Data", paste("raw-data_", date_string, ".rds", sep = ""))
)

# -----------------------------------------------------------------------------

flat_data <- full_data %>%
  rowwise() %>%
  mutate(studies = paste(studies, collapse = " | ")) %>%
  ungroup()

write_csv(
  flat_data,
  file.path("..", "Data", paste("raw-data_", date_string, ".csv", sep = ""))
)

col_types <- flat_data %>%
  summarise(across(.fns = type_sum)) %>%
  gather(col_name, col_type)
write_csv(
  col_types,
  file.path("..", "Data", paste("raw-data_", date_string, "_types.csv", sep = ""))
)

###############################################################################
